import { openApiDocumentB4 as baseDocument } from "./openapi-b4.js";

const dataResponse = (description: string, schemaRef: string) => ({
  description,
  content: {
    "application/json": {
      schema: {
        type: "object",
        required: ["data"],
        properties: { data: { $ref: schemaRef } },
      },
    },
  },
});

const fileIdParameter = {
  name: "fileId",
  in: "path",
  required: true,
  schema: { type: "string", pattern: "^[a-fA-F0-9]{24}$" },
} as const;

export const openApiDocumentB5 = {
  ...baseDocument,
  info: {
    ...baseDocument.info,
    version: "1.0.0-b5",
    description:
      "Authoritative 2026 API contract. B5 adds authenticated private-file handling outside the webroot, content-signature validation, opaque storage keys, owner/admin authorization and recoverable post-commit side-effect delivery. SMTP delivery is explicitly at-least-once rather than falsely claiming distributed exactly-once semantics.",
  },
  paths: {
    ...baseDocument.paths,
    "/files": {
      get: {
        summary: "List active private files in the authorized owner scope",
        security: [{ cookieSession: [] }],
        parameters: [
          {
            name: "ownerId",
            in: "query",
            description: "Admin-only override; omitted means the current user",
            schema: { type: "string", pattern: "^[a-fA-F0-9]{24}$" },
          },
        ],
        responses: {
          "200": dataResponse(
            "Private file metadata list",
            "#/components/schemas/PrivateFileList",
          ),
          "400": { $ref: "#/components/responses/ValidationError" },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "403": { $ref: "#/components/responses/Forbidden" },
          "503": { $ref: "#/components/responses/ServiceUnavailable" },
        },
      },
    },
    "/files/{purpose}": {
      post: {
        summary: "Upload one private file for the current authenticated user",
        description:
          "Exactly one multipart field named `file`. The server validates purpose policy, declared MIME type, filename extension and magic bytes before activating the blob. Storage filenames are generated by the server and are never exposed.",
        security: [{ cookieSession: [] }],
        parameters: [
          {
            name: "purpose",
            in: "path",
            required: true,
            schema: {
              type: "string",
              enum: [
                "avatar",
                "premium-identification",
                "premium-address",
                "premium-bank-statement",
              ],
            },
          },
        ],
        requestBody: {
          required: true,
          content: {
            "multipart/form-data": {
              schema: {
                type: "object",
                required: ["file"],
                properties: {
                  file: { type: "string", format: "binary" },
                },
              },
            },
          },
        },
        responses: {
          "201": dataResponse("Private file metadata", "#/components/schemas/PrivateFile"),
          "400": { $ref: "#/components/responses/ValidationError" },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "403": { $ref: "#/components/responses/Forbidden" },
          "409": { $ref: "#/components/responses/Conflict" },
          "413": { description: "File exceeds the configured purpose/request limit" },
          "415": { description: "File type, extension, declared MIME or signature is not allowed" },
          "503": { $ref: "#/components/responses/ServiceUnavailable" },
        },
      },
    },
    "/files/{fileId}": {
      get: {
        summary: "Read authorized private-file metadata",
        security: [{ cookieSession: [] }],
        parameters: [fileIdParameter],
        responses: {
          "200": dataResponse("Private file metadata", "#/components/schemas/PrivateFile"),
          "400": { $ref: "#/components/responses/ValidationError" },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "503": { $ref: "#/components/responses/ServiceUnavailable" },
        },
      },
      delete: {
        summary: "Delete an authorized private file",
        security: [{ cookieSession: [] }],
        parameters: [fileIdParameter],
        responses: {
          "204": { description: "Private file moved through the recoverable deletion lifecycle" },
          "400": { $ref: "#/components/responses/ValidationError" },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "403": { $ref: "#/components/responses/Forbidden" },
          "404": { $ref: "#/components/responses/NotFound" },
          "503": { $ref: "#/components/responses/ServiceUnavailable" },
        },
      },
    },
    "/files/{fileId}/content": {
      get: {
        summary: "Download authorized private-file content",
        security: [{ cookieSession: [] }],
        parameters: [fileIdParameter],
        responses: {
          "200": {
            description: "Private file content served as an attachment with nosniff and no-store headers",
            headers: {
              "Content-Disposition": { schema: { type: "string" } },
              "X-Content-Type-Options": { schema: { type: "string", const: "nosniff" } },
            },
            content: {
              "image/jpeg": { schema: { type: "string", format: "binary" } },
              "image/png": { schema: { type: "string", format: "binary" } },
              "image/webp": { schema: { type: "string", format: "binary" } },
              "application/pdf": { schema: { type: "string", format: "binary" } },
            },
          },
          "400": { $ref: "#/components/responses/ValidationError" },
          "401": { $ref: "#/components/responses/Unauthorized" },
          "404": { $ref: "#/components/responses/NotFound" },
          "503": { $ref: "#/components/responses/ServiceUnavailable" },
        },
      },
    },
  },
  components: {
    ...baseDocument.components,
    schemas: {
      ...baseDocument.components.schemas,
      PrivateFile: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "ownerId",
          "purpose",
          "originalName",
          "mediaType",
          "bytes",
          "sha256",
          "createdAt",
        ],
        properties: {
          id: { type: "string", pattern: "^[a-fA-F0-9]{24}$" },
          ownerId: { type: "string" },
          purpose: {
            type: "string",
            enum: [
              "avatar",
              "premium-identification",
              "premium-address",
              "premium-bank-statement",
            ],
          },
          originalName: { type: "string", minLength: 1, maxLength: 120 },
          mediaType: {
            type: "string",
            enum: ["image/jpeg", "image/png", "image/webp", "application/pdf"],
          },
          bytes: { type: "integer", minimum: 1, maximum: 5_242_880 },
          sha256: { type: "string", pattern: "^[a-f0-9]{64}$" },
          createdAt: { type: "string", format: "date-time" },
        },
      },
      PrivateFileList: {
        type: "object",
        additionalProperties: false,
        required: ["items"],
        properties: {
          items: {
            type: "array",
            maxItems: 4,
            items: { $ref: "#/components/schemas/PrivateFile" },
          },
        },
      },
    },
  },
} as const;
