openapi: 3.0.1
info:
  title: API Categories
  version: 1.0.0
paths:
  /api/categories:
    get:
      summary: Obtener todas las categorias
      tags:
        - Categories
      responses:
        200:
          description: Se obtuvo la lista de categorias correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        500:
          description: Error interno del servidor.
        400:
          description: Error en los parámetros de entrada.
    post:
      summary: Crear una nueva categoria.
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createCategory'
      responses:
        200:
          description: Se creó la categoria correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        500:
          description: Error interno del servidor.
        400:
          description: Error en los parámetros de entrada.
  /api/categories/{id}:
    put:
      summary: Actualizar visibilidad de una categoria.
      tags:
        - Categories
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $type: integer
          description: ID de la categoria a actualizar.
      responses:
        200:
          description: Se actualizó la categoria correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        500:
          description: Error interno del servidor.
        400:
          description: Error en los parámetros de entrada.
components:
  schemas:
    Category:
      type: object
      properties:
        _id:
          type: integer
        nameCategory:
          type: string
        isVisible:
          type: boolean
        description:
          type: string
      example:
        _id: 655c45f69dd5c1c11f0a6279
        nameCategory: Categoria Prueba
        isVisible: true
        description: Descripcion de la categoria Prueba.
  requestBodies:
    createCategory:
      description: Categoria a crear.
      required: true
      properties:
        nameCategory:
          type: string
          example: Categoria Prueba
        isVisible:
          type: boolean
          example: true
        description:
          type: string
          example: Descripcion de la categoria Prueba.
  


