const EnumError = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    INVALID_VALUES_ERROR: 3,
    DATABASE_ERROR: 4,
    DUPLICATE_EMAIL_ERROR: 5,
    WEAK_PASSWORD_ERROR: 6,
};

export default EnumError;